spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/**
        - id: EMPLOYEE-MASTER
          uri: lb://EMPLOYEE-MASTER
          predicates:
            - Path=/employee/**
        - id: SALARY-SERVICE
          uri: lb://SALARY-SERVICE
          predicates:
            - Path=/salary/**
        - id: ATTENDANCE
          uri: lb://ATTENDANCE
          predicates:
            - Path=/attendance/**

server:
  port: 8091


  main:
    web-application-type: reactive

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/realms/creative-main-microservice
