spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/Department?createTableIfNotExist=true
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka


management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health



  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      employeeSalaryBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT-BASED





























