spring:
  application:
    name: SALARY-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/salaryService?createTableIfNotExist=true
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8084
