package com.example.EmployeeMaster.Transformations;

import com.example.EmployeeMaster.Dtos.RequestDto.EmpRequestDto;
import com.example.EmployeeMaster.Dtos.ResponseDto.EmpResponseDto;
import com.example.EmployeeMaster.Models.Employee;

public class EmpTransformation {

    public static Employee convertEntity(EmpRequestDto empRequestDto){

        return Employee.builder()
                .dailyWageHours(empRequestDto.getDailyWageHours())
                .empAadhaarCardNo(empRequestDto.getEmpAadhaarCardNo())
                .empAge(empRequestDto.getEmpAge())
                .empBasicPay(empRequestDto.getEmpBasicPay())
                .empCatgCode(empRequestDto.getEmpCatgCode())
                .empCode(empRequestDto.getEmpCode())
                .empDOB(empRequestDto.getEmpDOB())
                .empDeptCode(empRequestDto.getEmpDeptCode())
                .empDesgCode(empRequestDto.getEmpDesgCode())
                .empDOJ(empRequestDto.getEmpDOJ())
                .empDOL(empRequestDto.getEmpDOL())
                .empEfpfTag(empRequestDto.getEmpEfpfTag())
                .empEmail(empRequestDto.getEmpEmail())
                .empImage(empRequestDto.getEmpImage())
                .empEpfTag(empRequestDto.getEmpEpfTag())
                .empESIDTag(empRequestDto.getEmpESIDTag())
                .empGuardianName(empRequestDto.getEmpGuardianName())
                .empGuardianRelations(empRequestDto.getEmpGuardianRelations())
                .empHealthIns(empRequestDto.getEmpHealthIns())
                .empLeftTag(empRequestDto.getEmpLeftTag())
                .empLunchTag(empRequestDto.getEmpLunchTag())
                .empLunchTime(empRequestDto.getEmpLunchTime())
                .empMaritalStatus(empRequestDto.getEmpMaritalStatus())
                .empMiscDed(empRequestDto.getEmpMiscDed())
                .empMotherName(empRequestDto.getEmpMotherName())
                .empName(empRequestDto.getEmpName())
                .empNationality(empRequestDto.getEmpNationality())
                .empNominee(empRequestDto.getEmpNominee())
                .empNomineeDOB(empRequestDto.getEmpNomineeDOB())
                .empNomineeRelations(empRequestDto.getEmpNomineeRelations())
                .empOverTimeTag(empRequestDto.getEmpOverTimeTag())
                .empPanNo(empRequestDto.getEmpPanNo())
                .empPaymentMode(empRequestDto.getEmpPaymentMode())
                .empPerHourWageTag(empRequestDto.getEmpPerHourWageTag())
                .empRelaxTime(empRequestDto.getEmpRelaxTime())
                .EmpReligion(empRequestDto.getEmpReligion())
                .empRemarks(empRequestDto.getEmpRemarks())
                .empSundayTag(empRequestDto.getEmpSundayTag())
                .empTds(empRequestDto.getEmpTds())
                .empTeaTag(empRequestDto.getEmpTeaTag())
                .empTeaTag2(empRequestDto.getEmpTeaTag2())
                .empTeaTime(empRequestDto.getEmpTeaTime())
                .empTeaTime2(empRequestDto.getEmpTeaTime2())
                .empTimeDedOnlyTag(empRequestDto.getEmpTimeDedOnlyTag())
                .empTimeInFirst(empRequestDto.getEmpTimeInFirst())
                .empTimeInLast(empRequestDto.getEmpTimeInLast())
                .empTimeOutFirst(empRequestDto.getEmpTimeOutFirst())
                .empTimeOutLast(empRequestDto.getEmpTimeOutLast())
                .empUnitCode(empRequestDto.getEmpUnitCode())
                .empWorkingHours(empRequestDto.getEmpWorkingHours())
                .gender(empRequestDto.getGender())
                .LunchBreakIn(empRequestDto.getLunchBreakIn())
                .LunchBreakOut(empRequestDto.getLunchBreakOut())
                .perHourWage(empRequestDto.getPerHourWage())
                .perHourWageTime(empRequestDto.getPerHourWageTime())
                .teaBreak1In(empRequestDto.getTeaBreak1In())
                .teaBreak1Out(empRequestDto.getTeaBreak1Out())
                .teaBreak2In(empRequestDto.getTeaBreak2In())
                .teaBreak2Out(empRequestDto.getTeaBreak2Out())
                .build();
    }


    public static EmpResponseDto convertIntoResponse(Employee employee){

        return EmpResponseDto.builder()
                .dailyWageHours(employee.getDailyWageHours())
                .empAadhaarCardNo(employee.getEmpAadhaarCardNo())
                .empAge(employee.getEmpAge())
                .empBasicPay(employee.getEmpBasicPay())
                .empCatgCode(employee.getEmpCatgCode())
                .empCode(employee.getEmpCode())
                .empDOB(employee.getEmpDOB())
                .empDeptCode(employee.getEmpDeptCode())
                .empDesgCode(employee.getEmpDesgCode())
                .empDOJ(employee.getEmpDOJ())
                .empDOL(employee.getEmpDOL())
                .empEfpfTag(employee.getEmpEfpfTag())
                .empEmail(employee.getEmpEmail())
                .empImage(employee.getEmpImage())
                .empEpfTag(employee.getEmpEpfTag())
                .empESIDTag(employee.getEmpESIDTag())
                .empGuardianName(employee.getEmpGuardianName())
                .empGuardianRelations(employee.getEmpGuardianRelations())
                .empHealthIns(employee.getEmpHealthIns())
                .empLeftTag(employee.getEmpLeftTag())
                .empLunchTag(employee.getEmpLunchTag())
                .empLunchTime(employee.getEmpLunchTime())
                .empMaritalStatus(employee.getEmpMaritalStatus())
                .empMiscDed(employee.getEmpMiscDed())
                .empMotherName(employee.getEmpMotherName())
                .empName(employee.getEmpName())
                .empNationality(employee.getEmpNationality())
                .empNominee(employee.getEmpNominee())
                .empNomineeDOB(employee.getEmpNomineeDOB())
                .empNomineeRelations(employee.getEmpNomineeRelations())
                .empOverTimeTag(employee.getEmpOverTimeTag())
                .empPanNo(employee.getEmpPanNo())
                .empPaymentMode(employee.getEmpPaymentMode())
                .empPerHourWageTag(employee.getEmpPerHourWageTag())
                .empRelaxTime(employee.getEmpRelaxTime())
                .EmpReligion(employee.getEmpReligion())
                .empRemarks(employee.getEmpRemarks())
                .empSundayTag(employee.getEmpSundayTag())
                .empTds(employee.getEmpTds())
                .empTeaTag(employee.getEmpTeaTag())
                .empTeaTag2(employee.getEmpTeaTag2())
                .empTeaTime(employee.getEmpTeaTime())
                .empTeaTime2(employee.getEmpTeaTime2())
                .empTimeDedOnlyTag(employee.getEmpTimeDedOnlyTag())
                .empTimeInFirst(employee.getEmpTimeInFirst())
                .empTimeInLast(employee.getEmpTimeInLast())
                .empTimeOutFirst(employee.getEmpTimeOutFirst())
                .empTimeOutLast(employee.getEmpTimeOutLast())
                .empUnitCode(employee.getEmpUnitCode())
                .empWorkingHours(employee.getEmpWorkingHours())
                .gender(employee.getGender())
                .LunchBreakIn(employee.getLunchBreakIn())
                .LunchBreakOut(employee.getLunchBreakOut())
                .perHourWage(employee.getPerHourWage())
                .perHourWageTime(employee.getPerHourWageTime())
                .teaBreak1In(employee.getTeaBreak1In())
                .teaBreak1Out(employee.getTeaBreak1Out())
                .teaBreak2In(employee.getTeaBreak2In())
                .teaBreak2Out(employee.getTeaBreak2Out())
                .build();
    }
}
